# https://taskfile.dev

version: "3"

vars:
  PROJECT_NAME: dss-sequence-example

env:
  COMPOSE_PROJECT_NAME: "{{.PROJECT_NAME}}"

tasks:
  clean:
    desc: Clean up all containers, volumes, and generated files
    cmds:
      - docker compose down -v --remove-orphans
      - task: clean-certs

  setup-certs:
    desc: Generate SSL certificates for connectors
    deps: [clean-certs]
    cmds:
      - task: generate-certs
        vars:
          {
            CERT_DIR: "{{.ROOT_DIR}}/certs/dashboard",
            COMMON_NAME: dashboard_connector,
          }
      - task: generate-certs
        vars:
          { CERT_DIR: "{{.ROOT_DIR}}/certs/dss", COMMON_NAME: dss_connector }

  clean-certs:
    desc: Remove existing certificates
    cmds:
      - rm -rf {{.ROOT_DIR}}/certs

  generate-vault-properties:
    desc: Generate vault properties file with base64 encoded keys
    requires:
      vars: [CERT_DIR, CONNECTOR_NAME]
    cmds:
      - "{{.ROOT_DIR}}/scripts/generate-vault-properties.sh {{.CERT_DIR}} {{.CONNECTOR_NAME}}"
    status:
      - test -f {{.CERT_DIR}}/vault.properties

  generate-certs:
    desc: Generate certificates for a specific connector
    requires:
      vars: [CERT_DIR, COMMON_NAME]
    cmds:
      - mkdir -p {{.CERT_DIR}}
      - "{{.ROOT_DIR}}/scripts/generate-certs.sh {{.CERT_DIR}} {{.COMMON_NAME}}"
    status:
      - test -f {{.CERT_DIR}}/cert.pfx && test -f {{.CERT_DIR}}/vault.properties

  up:
    desc: Start the complete proof of concept environment
    deps: [setup-certs]
    cmds:
      - docker compose up -d --build --wait

  down:
    desc: Stop all services and remove containers
    cmds:
      - docker compose down -v

  restart:
    desc: Restart the entire environment
    cmds:
      - task: down
      - task: up

  logs:
    desc: Show logs from all services
    cmds:
      - docker compose logs -f

  status:
    desc: Show status of all containers
    cmds:
      - docker compose ps

  test-health:
    desc: Test health endpoints of all services
    cmds:
      - "{{.ROOT_DIR}}/scripts/test-health.sh"

  test-f1-request:
    desc: Test a complete DSS F1 (Energy Optimization) request flow
    cmds:
      - "{{.ROOT_DIR}}/scripts/test-f1-request.sh"
